name: VisionMD
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=2.2.0
  - alsa-lib=1.2.14
  - altgraph=0.17.3
  - anyio=4.7.0
  - aom=3.9.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asgiref=3.8.1
  - asttokens=3.0.0
  - astunparse=1.6.3
  - async-lru=2.0.4
  - attr=2.5.1
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - blas=2.131
  - blas-devel=3.9.0
  - bleach=6.2.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - comm=0.2.1
  - cuda-crt-tools=12.9.41
  - cuda-cudart=12.9.37
  - cuda-cudart_linux-64=12.9.37
  - cuda-cupti=12.9.19
  - cuda-nvcc-tools=12.9.41
  - cuda-nvrtc=12.9.41
  - cuda-nvtx=12.9.19
  - cuda-nvvm-tools=12.9.41
  - cuda-version=12.9
  - cudnn=9.10.0.56
  - cyrus-sasl=2.1.27
  - dav1d=1.2.1
  - dbus=1.13.18
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - django=5.2
  - django-cors-headers=4.7.0
  - djangorestframework=3.16.0
  - double-conversion=3.3.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.7.0
  - ffmpeg=7.1.0
  - flatbuffers=24.3.25
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freeglut=3.4.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - gast=0.6.0
  - gdk-pixbuf=2.42.12
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - giflib=5.2.2
  - glib=2.84.0
  - glib-tools=2.84.0
  - gmp=6.3.0
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - grpcio=1.62.2
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - h11=0.14.0
  - h2=4.2.0
  - h5py=3.13.0
  - harfbuzz=9.0.0
  - hdf5=1.14.3
  - hpack=4.1.0
  - httpcore=1.0.2
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imath=3.1.12
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=8.30.0
  - ipywidgets=8.1.5
  - jasper=4.2.5
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - keras=3.9.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libass=0.17.3
  - libblas=3.9.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libclang13=19.1.7
  - libcublas=12.9.0.13
  - libcudnn=9.10.0.56
  - libcudnn-dev=9.10.0.56
  - libcufft=11.4.0.6
  - libcups=2.3.3
  - libcurand=10.3.10.19
  - libcurl=8.13.0
  - libcusolver=11.7.4.40
  - libcusparse=12.5.9.5
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.4
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.0
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libgrpc=1.62.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm19=19.1.7
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.6
  - libnvjitlink=12.9.41
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopencv=4.10.0
  - libopenvino=2024.4.0
  - libopenvino-auto-batch-plugin=2024.4.0
  - libopenvino-auto-plugin=2024.4.0
  - libopenvino-hetero-plugin=2024.4.0
  - libopenvino-intel-cpu-plugin=2024.4.0
  - libopenvino-intel-gpu-plugin=2024.4.0
  - libopenvino-intel-npu-plugin=2024.4.0
  - libopenvino-ir-frontend=2024.4.0
  - libopenvino-onnx-frontend=2024.4.0
  - libopenvino-paddle-frontend=2024.4.0
  - libopenvino-pytorch-frontend=2024.4.0
  - libopenvino-tensorflow-frontend=2024.4.0
  - libopenvino-tensorflow-lite-frontend=2024.4.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.5
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librsvg=2.58.4
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.49.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=256.9
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.8.0
  - libxml2=2.13.5
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markdown=3.8
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.6
  - mdurl=0.1.2
  - mistune=3.1.2
  - mpg123=1.32.9
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - namex=0.0.9
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - nccl=2.26.5.1
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - nspr=4.36
  - nss=3.111
  - numpy=1.26.4
  - ocl-icd=2.3.2
  - openblas=0.3.29
  - opencv=4.10.0
  - openexr=3.2.2
  - openh264=2.5.0
  - openldap=2.6.9
  - openssl=3.5.0
  - opt_einsum=3.4.0
  - optree=0.15.0
  - overrides=7.4.0
  - packaging=25.0
  - pandoc=2.12
  - pandocfilters=1.5.0
  - pango=1.54.0
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.8.0
  - pip=25.1
  - pixman=0.46.0
  - platformdirs=4.3.7
  - ply=3.11
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protobuf=4.25.3
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pulseaudio-client=17.0
  - pure_eval=0.2.2
  - py-opencv=4.10.0
  - pycparser=2.22
  - pygments=2.19.1
  - pyinstaller=5.13.2
  - pyinstaller-hooks-contrib=2025.1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-flatbuffers=25.2.10
  - python-json-logger=3.2.1
  - python_abi=3.10
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt-main=5.15.15
  - qt6-main=6.8.1
  - qtconsole=5.6.1
  - qtpy=2.4.1
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=14.0.0
  - rpds-py=0.22.3
  - scipy=1.15.3
  - send2trash=1.8.2
  - setuptools=78.1.1
  - sip=6.7.12
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.32.3
  - sqlparse=0.5.2
  - stack_data=0.2.0
  - svt-av1=2.3.0
  - tbb=2022.0.0
  - tensorboard=2.17.1
  - tensorboard-data-server=0.7.0
  - tensorflow=2.17.0
  - tensorflow-base=2.17.0
  - tensorflow-estimator=2.17.0
  - tensorflow-hub=0.16.1
  - termcolor=3.1.0
  - terminado=0.17.1
  - tf-keras=2.17.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - urllib3=2.4.0
  - wayland=1.23.1
  - wayland-protocols=1.43
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - wrapt=1.17.2
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - attrs==25.3.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.18.0
      - fonttools==4.58.0
      - fsspec==2025.3.2
      - gunicorn==23.0.0
      - jax==0.5.0
      - jax-cuda12-pjrt==0.5.0
      - jax-cuda12-plugin==0.5.0
      - jaxlib==0.5.0
      - kiwisolver==1.4.8
      - lap==0.5.12
      - matplotlib==3.10.3
      - mediapipe==0.10.21
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - networkx==3.4.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvcc-cu12==12.9.41
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - opencv-contrib-python==4.11.0.86
      - pandas==2.2.3
      - pillow==11.2.1
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyparsing==3.2.3
      - pytz==2025.2
      - sentencepiece==0.2.0
      - sounddevice==0.5.2
      - sympy==1.14.0
      - torch==2.7.0
      - torchvision==0.22.0
      - triton==3.3.0
      - tzdata==2025.2
      - ultralytics==8.3.139
      - ultralytics-thop==2.0.14
      - waitress==3.0.2