pyinstaller serve_mac.py \
  --console \
  --onedir  \
  --distpath ./pyinstaller_builds \
  --add-data "VideoAnalysisToolBackend:VideoAnalysisToolBackend" \
  --add-data "app:app" \
  --clean \
  --noconfirm \
  --collect-all numpy \
  --collect-all scipy \
  --collect-all tensorflow \
  --collect-all keras \
  --collect-all torch \
  --collect-all torchvision \
  --collect-all opencv-python \
  --collect-all pandas \
  --collect-all matplotlib \
  --hidden-import=scipy._lib.array_api_compat.numpy.fft